sudo: required
language: cpp
compiler: gcc
dist: focal

before_install:
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6B05F25D762E3157
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  - sudo apt-get install -qq g++-11
 # - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 90

script: 
  - wget https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - chmod +x ./gcc-fix.sh
#  - sudo ln -s ./include/dt-bindings dt-bindings
  - chmod +x ./Z00T.sh
  - chmod +x ./Z00TQ.sh
  - chmod +x ./Z00L.sh
  - chmod +x ./Z00LQ.sh
  - sudo bash ./gcc-fix.sh
  #- sudo bash ./Z00T.sh
  - sudo bash ./Z00TQ.sh
  #- sudo bash ./Z00L.sh
  - sudo bash ./Z00LQ.sh

after_success:
  - export UPLOADTOOL_SUFFIX=QZ
  - export UPLOADTOOL_BODY="Custom Q Kernel for Z00T and Z00L Devices Without CC Stack Protector"
  - sudo bash upload.sh $TRAVIS_BUILD_DIR/msm8916/*.zip

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/

cache:
  - ccache

group: travis_latest
os: linux
